# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: ZhikeOnline.DocBoxReaderInstaller
PackageVersion: 2.12.36
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://www.daokeyuedu.com/docbox/%E7%A8%BB%E5%A3%B3%E9%98%85%E8%AF%BB%E5%99%A8%E5%AE%89%E8%A3%85%E7%A8%8B%E5%BA%8F.exe
  InstallerSha256: D42322ACAFEDB3BB68365FEC48848858ADD25E7D0627ACD0A8180F78A1ABEB2A
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /register /autoupdate
ManifestType: installer
ManifestVersion: 1.4.0
